name    'treydock-scl'
version '0.0.1'
source 'git://github.com/treydock/puppet-scl'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Manage Software Collections'
description 'Manage Software Collections'
project_page 'http://github.com/treydock/puppet-scl'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'